image: node:latest

pages:
  stage: deploy
  script:
  - sudo npm install -g redoc-cli
  - redoc-cli bundle -o public/index.html swagger/swagger.json
  artifacts:
    paths:
    - public
  only:
  - main