[project]
name = "observatory-api"
version = "2.7.23"
description = "REST API service for the Research Software Observatory"
requires-python = ">=3.11"
dependencies = [
    "cffconvert==2.0.0",
    "fairsoft_core==0.2.1",
    "fastapi==0.136.1",
    "pydantic==2.13.3",
    "pymongo==4.17.0",
    "PyYAML==6.0.3",
    "requests>=2.32.3",
    "pytest-asyncio==1.3.0"
]

[project.optional-dependencies]
dev = [
    "pytest==9.0.2",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"